import type { Metadata } from "next";
import * as stylex from "@stylexjs/stylex";
import { colors, fonts } from "./vars.stylex";
import { useState } from "react";
import ThemeControl from "./ThemeControl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html {...stylex.props(styles.html)} lang="en">
      <ThemeControl style={styles.body}>{children}</ThemeControl>
    </html>
  );
}

const styles = stylex.create({
  html: {
    colorScheme: "light dark",
    boxSizing: {
      default: "border-box",
      ":not(#_) *": "border-box",
    },
  },
  body: {
    color: colors.fg,
    backgroundColor: colors.bg,
    fontFamily: fonts.sans,
    WebkitFontSmoothing: "antialiased",
    MozOsxFontSmoothing: "grayscale",
  },
});
